workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /master/
#    - if: $CI_COMMIT_BRANCH =~ /filebeat-oss-7.8.0/
    # - if: $CI_COMMIT_BRANCH =~ /feat-cicd/

image: reg.deeproute.ai/deeproute-public/docker:19.03.12-bash

variables:
  GIT_DEPTH: "1"
  OS: "${CI_COMMIT_REF_NAME}"

stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - compilation
  only:
    - pushes
  script: |
    if [ "master" == "${CI_COMMIT_BRANCH}" ]; then
      for env_value in $(compgen -v |grep '.*_PRODUCTION$'); do
        eval export ${env_value%_PRODUCTION}="${!env_value}"
      done
    fi

    tag_build_num="0.0.${CI_PIPELINE_ID}"
    export IMAGE="${DOCKER_URL}/${DOCKER_NAMESPACE}/${CI_PROJECT_NAME}:$tag_build_num"
    export IMAGE_LATEST="${DOCKER_URL}/${DOCKER_NAMESPACE}/${CI_PROJECT_NAME}:latest"

    # build the final image
    docker build \
      -t "$IMAGE" \
      -t $IMAGE_LATEST \
      .

    # upload to harbor
    docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}" "${DOCKER_URL}"
    docker push "$IMAGE"
    docker push "$IMAGE_LATEST"
