# permissions for end users to view watchlogs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watchlog-viewer-role
rules:
- apiGroups:
  - crd.k8s.deeproute.cn
  resources:
  - watchlogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.k8s.deeproute.cn
  resources:
  - watchlogs/status
  verbs:
  - get
