input {
  kafka{
    bootstrap_servers => "kafka:9092"
    # topics => "demo-syslog"
    topics_pattern => ".*"
    consumer_threads => 1 #with kafka topics partitions same
    decorate_events => true #add Kafka metadata
    codec => "json"
    auto_offset_reset => "earliest"
    group_id => "LOGSTASH"
  }
}

filter {
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    #user => "kibana"
    #password => "lKdPgXsHnDH6QJFDlN"
    index => "%{[@metadata][kafka][topic]}-%{+YYYY.MM.dd}"
  }
}